### PR TITLE
Added Ability to choose custom port

### PR DESCRIPTION
**Pull request by ufoptg**
#### How can I use a custom port?
```python
torrent_file = TorrentDownloader("magnet/torrent.file", '.', port=0000)
```

### CODE REVIEW

**Comment by iw4p** [comment]
Hey, 
Thank you for your contribution. 
As I can see if user doesn't pass the port, it uses the default. Otherwise user can pass any port right? The interface seems pretty and straightforward.

**Comment by iw4p** [comment]
Please increase the version (0.2.0 is good in my opinion) so CI/CD can release the new version

**Comment by ufoptg** [comment]
Yes, everything is the same works like this 

optional for the user to use say 
```python
torrent_file = TorrentDownloader("magnet:...", '.', port=6969)
```

if no port is specified and it is used how it is below then the port will default to 6881 as it is now.


```python
import asyncio
from torrentp import TorrentDownloader
torrent_file = TorrentDownloader("magnet:...", '.')
# Start the download process
asyncio.run(torrent_file.start_download()) # start_download() is a asynchronous method 

# Pausing the download
torrent_file.pause_download()

# Resuming the download
torrent_file.resume_download()

# Stopping the download
torrent_file.stop_download()
```

**Example**
~_This is how i am using it_ 



```python
def download_torrent(loop, magnet_link, directory_path):
    async def download():
        downloader = TorrentDownloader(magnet_link, directory_path, port=6969)
        downloaded_folder = await downloader.start_download()
        return downloaded_folder

    return asyncio.run(download())
```

**Comment by ufoptg** [comment]
WIll do it a bit later on but would also be good idea to add --port to the CLI ill do that later on though :)

nice little code you wrote here... works well on telegram >.<

**Comment by iw4p** [comment]
Great, Thank you. Should I rebase it right now or wait for the CLI? 🤔

**Comment by ufoptg** [comment]
rebase it now :) ill find some time later on to do it :) unless someone else beats us to it lol

**Comment by iw4p** [comment]
Cool, sure! Ty again

**Comment by ufoptg** [comment]
thank you :) awesome little tool eh

**Comment by iw4p** [comment]
You're welcome! xD

**Pull request merged**
