### PR TITLE
Added Stop / Resume / Pause

### PR DESCRIPTION
**Pull request by ufoptg**
async
and stop pause and resume added

### CODE REVIEW

**Comment by iw4p** [comment]
Hi! Thank you for your great contribution!
Did you test all modules and functionalities? Is it ready to be merged?

**Comment by ufoptg** [comment]
everything seems to be working for me just need to remember to await the async functions

**Comment by iw4p** [comment]
Thank you!
Whenever you think your changes are done, tell me to merge your pull request.

**Comment by ufoptg** [comment]
No worries, as long as you understand asynchronous functions I'll leave it as its you can merge I will change some more later on. But it's working for me how I need at the moment

**Pull request merged**
