### PR TITLE
Feat(CLI): Command Line Interface

### PR DESCRIPTION
**Pull request by abieru**
## what did I do?

- New command ```torrentp``` to use as a CLI
```sh
 $ torrentp --link 'magnet:...'
```

- changing Downloader message, to improve readability of download progress
- visual loading progress

WhatsApp Image 2024-03-23 at 01 19 25 (1)

- Update the README.md documenting the alterations made

### CODE REVIEW

**Comment by iw4p** [comment]
Wow excellent! Thank you for your contribution. I'll test the old functionality and check it out fully ASAP! Ty again!

**Comment by abieru** [comment]
Nice! if there are any suggestions for changes in the code just let me know!

**Comment by iw4p** [comment]
At the beginning I was thinking about adding some cloud storage services to it (like my Telegram-cloud repo) or other repos to upload your torrent files to your Google drive or dropbox. So by download it, you have it on your cloud drive too. (If you run it on google colab or VPS, it's just like you transferred your file from torrent to cloud storage with $0.)

**Comment by abieru** [comment]
It is an interesting idea, I'm going to take a look at your telegram-cloud repo :D

**Comment by abieru** [comment]
I found a way using a library called [pydrive2,](https://github.com/iterative/PyDrive2) which uses oAuth authentication, I am going to try to implement it. 
One thing that the developer who uses torrentp will have to do is to create a project in [Google Apis](https://console.cloud.google.com/iam-admin/projects)
(then other user can use the same project of Google Api)
Which I will do:
- I am going to try to create a temporary file that is progressively uploaded to google drive.
- The user can use it with the CLI or with a script using torrentp.

maybe it will take a while, do you think it is possible to make these alterations in another PR?

**Comment by iw4p** [comment]
I'll take a close look at it ASAP. I haven't check the functionality of src yet. If you can confirm it and you're sure about it, I can rebase it right now.

**Comment by abieru** [comment]
I will take another look at the functionalities and if everything is ok I will let you know if it is safe.  :D

**Comment by iw4p** [comment]
Tyyyy :DDDDDD

**Comment by ufoptg** [comment]
@abieru good job i was about to take a look at some of this

i use nohup to run some of my applications and when it calls torrentp my nohup.out file goes up to 50+mb lol from all the print statements lol

ill have a look at the changes youve made :)

**Comment by abieru** [comment]
I did some tests with 1gb torrents using the CLI or the classic way with a script and everything is ok. I think it is safe to merge, the main functions work correctly for me :D

**Comment by ufoptg** [comment]
@abieru 
> I did some tests with 1gb torrents using the CLI or the classic way with a script and everything is ok. I think it is safe to merge, the main functions work correctly for me :D

I tested too from a clean install from your fork, one thing i noticed needs to be added but other than that yes CLI seemed to work fine, and so did just normal way

**Comment by abieru** [comment]
one thing I couldn't figure out how to add to the CLI was, pause / stop / resume xD

**Comment by ufoptg** [comment]
> one thing I couldn't figure out how to add to the CLI was, pause / stop / resume xD

i willl have a look, i did a PR to add the missing install requirement to your fork

**Comment by abieru** [comment]
@ufoptg great! I've already merged it to my branch

**Comment by ufoptg** [comment]
@abieru i have a few different ways to add the stop resume and pause

**Comment by ufoptg** [comment]
This way is simple 
`import asyncclick as click
import asyncio

from .torrent_downloader import TorrentDownloader


@click.command()
@click.option('--link', required=True, help="Torrent link. Example: [--link 'file.torrent'] or [--link 'magnet:...']", type=str)
@click.option('--download_speed',  default=0, help='Download speed with a specific number (kB/s). Default: 0, means unlimited speed', type=int)
@click.option('--upload_speed',  default=0, help='Upload speed with a specific number (kB/s). Default: 0, means unlimited speed', type=int)
@click.option('--save_path',  default='.', help="Path to save the file, default: '.' ", type=str)
@click.option('--action', default='download', help='Action to perform: download, pause, resume, stop', type=str)
async def run_cli(link, download_speed, upload_speed, save_path, action):
    try:
        torrent_file = TorrentDownloader(link, save_path)
        
        if action == 'pause':
            torrent_file.pause_download()
        elif action == 'resume':
            torrent_file.resume_download()
        elif action == 'stop':
            torrent_file.stop_download()
        else:
            await torrent_file.start_download(download_speed=download_speed, upload_speed=upload_speed)

    except asyncio.TimeoutError or KeyboardInterrupt:
        print("The Program is terminated manually!")
        raise SystemExit


if __name__ == '__main__':
    run_cli(_anyio_backend="asyncio")`
    

But im kinda looking at a way we can just type input to stop / resume / pause

**Comment by ufoptg** [comment]
> one thing I couldn't figure out how to add to the CLI was, pause / stop / resume xD

You could try this method too, this should allow you to pause stop and resume while downloading using the CLI ill test it a bit later :)


```import asyncclick as click
import asyncio

from .torrent_downloader import TorrentDownloader


async def monitor_download_progress(torrent_file):
    while not torrent_file.is_complete():
        await asyncio.sleep(1)
        torrent_file.print_progress()


async def handle_input(torrent_file):
    while True:
        action = await asyncio.get_event_loop().run_in_executor(None, input, "Enter action (pause/resume/stop): ")
        if action.lower() == 'pause':
            torrent_file.pause_download()
        elif action.lower() == 'resume':
            torrent_file.resume_download()
        elif action.lower() == 'stop':
            torrent_file.stop_download()
        else:
            print("Invalid action. Please enter 'pause', 'resume', or 'stop'.")


@click.command()
@click.option('--link', required=True, help="Torrent link. Example: [--link 'file.torrent'] or [--link 'magnet:...']", type=str)
@click.option('--download_speed',  default=0, help='Download speed with a specific number (kB/s). Default: 0, means unlimited speed', type=int)
@click.option('--upload_speed',  default=0, help='Upload speed with a specific number (kB/s). Default: 0, means unlimited speed', type=int)
@click.option('--save_path',  default='.', help="Path to save the file, default: '.' ", type=str)
async def run_cli(link, download_speed, upload_speed, save_path):
    try:
        torrent_file = TorrentDownloader(link, save_path)
        
        input_task = asyncio.create_task(handle_input(torrent_file))
        progress_task = asyncio.create_task(monitor_download_progress(torrent_file))
        download_task = asyncio.create_task(torrent_file.start_download(download_speed=download_speed, upload_speed=upload_speed))
        
        await asyncio.gather(input_task, progress_task, download_task)

    except asyncio.TimeoutError or KeyboardInterrupt:
        print("The Program is terminated manually!")
        raise SystemExit


if __name__ == '__main__':
    run_cli(_anyio_backend="asyncio")
```

**Comment by ufoptg** [comment]
@abieru ive implemented resume / pause / stop

**Comment by abieru** [comment]
Amazing work :0 @ufoptg , I merge it, really nice work!! 
I think now everything is ok about the PR @iw4p xD

**Comment by iw4p** [comment]
Fantastic! I rebased the commits. Is there anything I should do? The version's fine also, CI/CD will release the latest version (0.2.0)

**Comment by iw4p** [comment]
It's on 0.1.9 🤔
[https://pypi.org/project/torrentp/](https://pypi.org/project/torrentp/)

Edit: version is correct ✅ my mistake 🫡

**Comment by abieru** [comment]
Nice i think everything is ok, the version actually is 0.1.9, @ufoptg change it, everything is ok! :D

**Comment by iw4p** [comment]
Yeah it's fine now :D great job 
Thank you guys

**Pull request merged**
